title: Privacytools-ru - Шифрование против глобального массового слежения
description: За тобой следят. Частные и спонсированные государством организации собирают данные о твоей Интернет-активности.
url: "https://privacytools-ru.github.io/"
sass:
  style: compressed
plugins:
  - jekyll-sitemap
sitemap:
file: "/sitemap.xml"
include: [".well-known"]
